### ISSUE TITLE
Imports issue. 

### ISSUE THREAD

**Issue by tigrus** [cgarciae/phi#1]
I don't know, where I found link to this library. But. Please change all lines like `from utils import identity` to `from .utils import identity`. 

You are not alone in the world, and currently lib doesn't work after `pip install phi`.

**Comment by cgarciae** [comment]
Hi @tigrus .

I just tested a fresh install of the library with docker and it work just fine:

```
docker run -it python:2.7 bash -c "pip install phi && python -c 'from phi import P; f = P + 1; print(f(1))'" 
```

What version do you have? The latest is `0.3.2`.

**Comment by cgarciae** [comment]
I'll look in the `.` business, I've seen it but I've never used it.

**Comment by cgarciae** [comment]
Ok just tested, I doesn't work in Python 3+. I'll look into it.

**Comment by cgarciae** [comment]
Fixed.

**Comment by tigrus** [comment]
Yep, problems were with python3

**Comment by cgarciae** [comment]
Nice. @tigrus I would appreciate any kind of feedback on: API, documentation, etc.
